import React from "react";

const BookItem = ({ coverImage, title, excerpt }) => {
  return (
    <div className="w-full sm:w-[calc(33.333%-20px)] mb-10 bg-accent dark:bg-[#ffffff0d] rounded-lg p-5 transition-transform duration-300 ease-in-out hover:translate-y-[-10px] flex flex-col items-center">
      <div
        style={{ backgroundImage: `url(${coverImage})` }}
        className="w-full h-[200px] sm:w-[200px] sm:h-[300px] bg-contain bg-center bg-no-repeat rounded-md flex justify-center items-center font-bold text-textPrimary text-lg text-center p-2"
      ></div>
      <h3 className="text-center text-primaryBg text-xl font-semibold mt-4 mb-2">{title}</h3>
      <p className="italic text-[#e1e1e1b0] mb-4">{excerpt}</p>
      <a
        href="#"
        className="inline-block text-accent no-underline transition-colors duration-300 ease-in-out hover:text-textPrimary"
      >
        Read More
      </a>
    </div>
  );
};

const BookSamples = () => {
  return (
    <section className="mt-20 px-4 text-center">
      <h2 className="text-3xl font-semibold mb-3">Sample Books Generated by BookAI</h2>
      <p className="text-lg mb-10">
        Explore some of the captivating books created using our AI technology.
      </p>
      <div className="flex flex-wrap justify-center gap-4">
        <BookItem
          coverImage="https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png"
          title="Science Fiction"
          excerpt={`"As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."`}
        />
        <BookItem
          coverImage="https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png"
          title="Mystery"
          excerpt={`"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."`}
        />
        <BookItem
          coverImage="https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png"
          title="Fantasy"
          excerpt={`"The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath..."`}
        />
      </div>
    </section>
  );
};

export default BookSamples;
