import React from "react";

const BookItem = ({ coverImage, title, excerpt }) => {
  return (
    <div className="basis-[calc(33.333%-40px)] mb-10 bg-[rgba(255,255,255,0.05)] rounded-lg p-5 transition-transform duration-300 ease-in-out hover:transform hover:translate-y-[-10px]">
      <div
        style={{ backgroundImage: `url(${coverImage})` }}
        className="w-[200px] h-[300px] mx-auto mb-5 bg-cover bg-center bg-no-repeat rounded-[5px] flex justify-center items-center font-bold text-textPrimary text-lg text-center p-2"
      ></div>
      <h3 className="text-center text-2xl font-semibold mb-2">{title}</h3>
      <p className="italic text-textSecondary mb-2">{excerpt}</p>
      <a
        href="#"
        className="inline-block mt-2 text-accent no-underline transition-colors duration-300 ease-in-out hover:text-textPrimary"
      >
        Read More
      </a>
    </div>
  );
};

const BookSamples = () => {
  return (
    <section className="mt-[80px] text-center">
      <h2 className="mb-10 text-2xl text-white text-center font-semibold">
        Sample Books Generated by BookAI
      </h2>
      <p>
        Explore some of the captivating books created using our AI technology.
      </p>
      <div className="flex justify-around flex-wrap mt-10">
        <BookItem
          coverImage="https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png"
          title="Science Fiction"
          excerpt={`"As Dr. Elara stepped through the shimmering portal, she knew
                    there was no turning back. The fate of two universes now rested in
                    her hands..."`}
        />
        <BookItem
          coverImage="https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png"
          title="Mystery"
          excerpt={`"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."`}
        />
        <BookItem
          coverImage="https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png"
          title="Fantasy"
          excerpt={`"The ancient prophecy spoke of a child born with starlight in
                    their eyes. As the comet blazed overhead, the kingdom held its
                    breath..."`}
        />
      </div>
    </section>
  );
};

export default BookSamples;
